# Server
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bloodbridge
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=bG9uZ1NlY3JldEtleUZvckJsb29kQnJpZGdlQXBwbGljYXRpb25TZWNyZXRLZXkxMjM0NTY3ODk=
jwt.expiration=86400000

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# File upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload.dir=uploads/documents

# Logging
logging.level.com.bloodbridge=DEBUG

# OTP Configuration
otp.expiry-minutes=5
otp.max-attempts=5
otp.rate-limit.max-requests=3
otp.rate-limit.window-minutes=10

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=santosh124gupta2002@gmail.com
spring.mail.password=cfbo wbfx orzr ateb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
