# Server
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bloodbridge
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=bG9uZ1NlY3JldEtleUZvckJsb29kQnJpZGdlQXBwbGljYXRpb25TZWNyZXRLZXkxMjM0NTY3ODk=
jwt.expiration=86400000

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# Logging
logging.level.com.bloodbridge=DEBUG
